"""Base module — Action declarations for Command Palette."""
from orbiteus_core.ai import Action, ActionCategory

ACTIONS = [
    Action(
        id="base.company.list",
        label="Companies",
        keywords=["companies", "company list", "organizations", "firms"],
        description="List of companies and organizations",
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/base/company",
        icon="building",
    ),
    Action(
        id="base.user.list",
        label="Users",
        keywords=["users", "user list", "accounts", "team members"],
        description="Manage system users",
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/base/user",
        icon="users",
    ),
    Action(
        id="base.partner.list",
        label="Partners",
        keywords=["partners", "vendors", "suppliers", "contacts", "partner list"],
        description="List of partners and contacts",
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/base/partner",
        icon="address-book",
    ),
    Action(
        id="technical.params",
        label="System Parameters",
        keywords=["parameters", "config", "system config", "settings", "system params"],
        description="Global system configuration parameters (IrConfigParam)",
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/technical/params",
        icon="adjustments",
    ),
    Action(
        id="technical.access",
        label="Access Rights",
        keywords=["access", "rbac", "permissions", "roles", "security", "access rights"],
        description="Manage model access rights (ir_model_access)",
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/technical/access",
        icon="shield-lock",
    ),
    Action(
        id="technical.sequences",
        label="Sequences",
        keywords=["sequences", "numbering", "document numbers", "sequence list"],
        description="Manage document numbering sequences",
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/technical/sequences",
        icon="list-numbers",
    ),
    Action(
        id="technical.crons",
        label="Cron Jobs",
        keywords=["cron", "cron jobs", "scheduled jobs", "scheduler", "automation"],
        description="Scheduled automated tasks",
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/technical/crons",
        icon="clock-play",
    ),
]
