"""CRM Action declarations (canonical: Person/Lead/Stage/Team)."""
from orbiteus_core.ai import Action, ActionCategory

ACTIONS = [
    # --- Persons ---
    Action(
        id="crm.person.list",
        label="Persons",
        keywords=["persons", "contacts", "people", "list of persons"],
        description="List of CRM persons (lead/customer/contact)",
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/crm/person",
        requires_feature="crm.persons.view",
        icon="users",
    ),
    Action(
        id="crm.person.create",
        label="Create Person",
        keywords=["new person", "add contact", "create person"],
        description="Open the form to create a person",
        category=ActionCategory.CREATE,
        target="navigate",
        target_url="/crm/person/new",
        requires_feature="crm.persons.manage",
        icon="user-plus",
    ),
    # --- Leads ---
    Action(
        id="crm.lead.list",
        label="Leads",
        keywords=["leads", "pipeline", "opportunities", "deals"],
        description="Sales leads (kanban available)",
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/crm/lead",
        requires_feature="crm.leads.view",
        icon="briefcase",
    ),
    Action(
        id="crm.lead.create",
        label="Create Lead",
        keywords=["new lead", "add lead", "new deal"],
        description="Open the form to create a lead",
        category=ActionCategory.CREATE,
        target="navigate",
        target_url="/crm/lead/new",
        requires_feature="crm.leads.manage",
        icon="briefcase",
    ),
    Action(
        id="crm.lead.move_stage",
        label="Move lead to stage",
        keywords=["change stage", "advance lead", "move pipeline"],
        description="Update the stage of an existing lead",
        category=ActionCategory.EXECUTE,
        target="api",
        target_url="/api/crm/lead/{id}/move",
        requires_feature="crm.leads.manage",
        icon="arrow-right",
    ),
    # --- Stages / Teams ---
    Action(
        id="crm.stage.list",
        label="Stages",
        keywords=["stages", "pipeline stages"],
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/crm/stage",
        requires_feature="crm.stages.view",
        icon="list",
    ),
    Action(
        id="crm.team.list",
        label="Sales teams",
        keywords=["teams", "sales team"],
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/crm/team",
        requires_feature="crm.teams.view",
        icon="user-group",
    ),
]
