"""CRM Action declarations (SPEC-001..005)."""
from orbiteus_core.ai import Action, ActionCategory

ACTIONS = [
    Action(
        id="crm.prospect.list",
        label="Prospect inbox",
        keywords=["prospects", "inbox", "leads inbox", "pre-pipeline"],
        description="Pre-pipeline prospects awaiting qualification",
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/crm/prospect?filter=inbox",
        requires_feature="crm.prospects.view",
        icon="inbox",
    ),
    Action(
        id="crm.prospect.create",
        label="Create prospect",
        keywords=["new prospect", "add lead inbox"],
        category=ActionCategory.CREATE,
        target="navigate",
        target_url="/crm/prospect/new",
        requires_feature="crm.prospects.manage",
        icon="user-plus",
    ),
    Action(
        id="crm.prospect.convert",
        label="Convert prospect to deal",
        keywords=["convert prospect", "qualify", "promote to pipeline"],
        description="Convert pre-pipeline prospect into a pipeline deal",
        category=ActionCategory.EXECUTE,
        target="api",
        target_url="/api/crm/prospect/{id}/convert",
        requires_feature="crm.prospects.manage",
        icon="arrow-right-circle",
        parameters_schema={
            "type": "object",
            "properties": {
                "id": {"type": "string", "description": "UUID of crm.prospect"},
                "pipeline_id": {
                    "type": "string",
                    "description": "UUID of crm.pipeline (default pipeline if omitted)",
                },
                "stage_id": {
                    "type": "string",
                    "description": "Optional UUID of crm.stage",
                },
                "expected_revenue": {
                    "type": "number",
                    "description": "Expected deal value",
                },
            },
            "required": ["id"],
        },
    ),
    Action(
        id="crm.organization.list",
        label="Organizations",
        keywords=["companies", "accounts", "organizations"],
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/crm/organization",
        requires_feature="crm.organizations.view",
        icon="building",
    ),
    Action(
        id="crm.organization.create",
        label="Create organization",
        keywords=["new company", "add account"],
        category=ActionCategory.CREATE,
        target="navigate",
        target_url="/crm/organization/new",
        requires_feature="crm.organizations.manage",
        icon="building-plus",
    ),
    Action(
        id="crm.person.list",
        label="Contacts",
        keywords=["persons", "contacts", "people"],
        description="CRM contacts linked to organizations",
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/crm/person",
        requires_feature="crm.persons.view",
        icon="users",
    ),
    Action(
        id="crm.person.create",
        label="Create contact",
        keywords=["new person", "add contact", "create person"],
        category=ActionCategory.CREATE,
        target="navigate",
        target_url="/crm/person/new",
        requires_feature="crm.persons.manage",
        icon="user-plus",
    ),
    Action(
        id="crm.lead.list",
        label="Deals pipeline",
        keywords=["leads", "pipeline", "deals", "kanban"],
        description="Sales deals in pipeline (kanban)",
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/crm/lead?view=kanban",
        requires_feature="crm.leads.view",
        icon="briefcase",
    ),
    Action(
        id="crm.lead.create",
        label="Create deal",
        keywords=["new deal", "add lead", "new opportunity"],
        category=ActionCategory.CREATE,
        target="navigate",
        target_url="/crm/lead/new",
        requires_feature="crm.leads.manage",
        icon="briefcase",
    ),
    Action(
        id="crm.lead.move_stage",
        label="Move deal to stage",
        keywords=["change stage", "advance deal", "move pipeline"],
        category=ActionCategory.EXECUTE,
        target="api",
        target_url="/api/crm/lead/{id}/move",
        requires_feature="crm.leads.manage",
        icon="arrow-right",
        parameters_schema={
            "type": "object",
            "properties": {
                "id": {"type": "string", "description": "UUID of crm.lead"},
                "stage_id": {"type": "string", "description": "UUID of target crm.stage"},
            },
            "required": ["id", "stage_id"],
        },
    ),
    Action(
        id="crm.activity.today",
        label="Today's activities",
        keywords=["today", "tasks", "calls", "meetings", "my day"],
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/crm/activity?filter=today",
        requires_feature="crm.activities.view",
        icon="calendar",
    ),
    Action(
        id="crm.leads.rotting",
        label="Rotting deals",
        keywords=["stale", "rotting", "stuck deals", "overdue pipeline"],
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/crm/lead?filter=rotting",
        requires_feature="crm.leads.view",
        icon="alert-triangle",
    ),
    Action(
        id="crm.pipeline.list",
        label="Pipelines",
        keywords=["pipelines", "sales motions"],
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/crm/pipeline",
        requires_feature="crm.pipelines.view",
        icon="git-branch",
    ),
    Action(
        id="crm.stage.list",
        label="Stages",
        keywords=["stages", "pipeline stages"],
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/crm/stage",
        requires_feature="crm.stages.view",
        icon="list",
    ),
    Action(
        id="crm.team.list",
        label="Sales teams",
        keywords=["teams", "sales team"],
        category=ActionCategory.NAVIGATE,
        target="navigate",
        target_url="/crm/team",
        requires_feature="crm.teams.view",
        icon="user-group",
    ),
]
