"""CRM module manifest — Pipedrive-class extensions (SPEC-001..008)."""

MANIFEST = {
    "name": "CRM",
    "version": "0.4.0",
    "depends_on": ["base", "auth"],
    "models": [
        "crm.organization",
        "crm.pipeline",
        "crm.person",
        "crm.stage",
        "crm.team",
        "crm.lead",
        "crm.prospect",
        "crm.activity",
        "crm.stage_history",
        "crm.automation_rule",
        "crm.queue",
    ],
    "category": "Sales",
    "auto_install": False,
    "data": [
        "security/access.yaml",
        "view/stage_views.xml",
        "view/lead_views.xml",
        "view/prospect_views.xml",
        "view/organization_views.xml",
        "view/person_views.xml",
        "view/activity_views.xml",
        "view/pipeline_views.xml",
        "view/queue_views.xml",
    ],
    "menus": [
        {"name": "CRM",            "sequence": 10, "icon": "users"},
        {"name": "Prospects",      "parent": "CRM", "sequence": 5,  "model": "crm.prospect", "url": "/crm/prospect?filter=inbox"},
        {"name": "Deals",          "parent": "CRM", "sequence": 10, "model": "crm.lead", "url": "/crm/lead?view=kanban"},
        {"name": "Organizations",  "parent": "CRM", "sequence": 15, "model": "crm.organization"},
        {"name": "Contacts",       "parent": "CRM", "sequence": 20, "model": "crm.person"},
        {"name": "Activities",     "parent": "CRM", "sequence": 25, "model": "crm.activity", "url": "/crm/activity?filter=today"},
        {"name": "Pipelines",      "parent": "CRM", "sequence": 30, "model": "crm.pipeline"},
        {"name": "Stages",         "parent": "CRM", "sequence": 35, "model": "crm.stage"},
        {"name": "Teams",          "parent": "CRM", "sequence": 40, "model": "crm.team"},
        {"name": "Work queues",    "parent": "CRM", "sequence": 45, "model": "crm.queue"},
    ],
    "view_config": "modules.crm.view.config",
    "bootstrap": "modules.crm.bootstrap",
}
